# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-02 06:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='choices',
            field=models.IntegerField(blank=True, choices=[(0, '叉车--叉车司机(N2)'), (1, '叉车--场(厂)内专用机动车辆安全管理(A8)'), (2, '容器--场固定式压力容器操作(R1)'), (3, '容器--锅炉压力容器压力管道安全管理(全部)(A3)')], default=0, verbose_name='培训项目'),
        ),
    ]
