# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-04-03 22:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0005_auto_20181021_1650'),
        ('users', '0005_auto_20181021_1650'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='problems.CourseTemp', verbose_name='培训项目'),
        ),
        migrations.AlterField(
            model_name='user',
            name='choices',
            field=models.IntegerField(blank=True, choices=[(0, '叉车司机'), (1, '叉车管理员'), (2, '压力容器操作员'), (3, '压力容器管理员'), (4, '电梯管理员'), (5, '电梯司机'), (6, '熔炉'), (7, '起重机司机'), (8, '起重机管理员'), (9, '安检--低压电工作业'), (10, '安检--高处作业'), (11, '安检--电焊'), (12, '特种设备管理员')], default=0, verbose_name='培训项目'),
        ),
    ]
