# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-09 14:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChapterTemp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.IntegerField(verbose_name='知识模块id')),
                ('course', models.IntegerField(verbose_name='所属项目num')),
                ('name', models.CharField(max_length=100, verbose_name='知识模块')),
            ],
            options={
                'verbose_name_plural': '知识模块(未处理)',
                'verbose_name': '知识模块(未处理)',
                'db_table': 'chapters_temp',
            },
        ),
        migrations.CreateModel(
            name='CourseTemp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.IntegerField(verbose_name='项目id')),
                ('name', models.CharField(max_length=100, verbose_name='项目名称')),
            ],
            options={
                'verbose_name_plural': '项目(未处理)',
                'verbose_name': '项目(未处理)',
                'db_table': 'courses_temp',
            },
        ),
        migrations.CreateModel(
            name='ProbelmTemp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.IntegerField(verbose_name='所属课程id')),
                ('chapter', models.IntegerField(verbose_name='所属章节id')),
                ('num', models.IntegerField(blank=True, null=True, verbose_name='序号')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='标题')),
                ('choices', models.CharField(blank=True, max_length=500, verbose_name='选择内容')),
                ('answers', models.CharField(blank=True, max_length=20, verbose_name='答案')),
                ('images', models.ImageField(blank=True, max_length=200, upload_to='yhpicture', verbose_name='图片')),
                ('category', models.IntegerField(choices=[(0, '单选题'), (1, '判断题'), (2, '多选题'), (3, '图片题')], default=0, verbose_name='题目类型')),
            ],
            options={
                'verbose_name_plural': '题目(未处理)',
                'verbose_name': '题目(未处理)',
                'db_table': 'problems_temp',
            },
        ),
    ]
