# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-08 05:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, verbose_name='章节名称')),
            ],
            options={
                'verbose_name': '章节名称',
                'db_table': 'chapters',
                'verbose_name_plural': '章节名称',
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, verbose_name='课程名称')),
            ],
            options={
                'verbose_name': '课程分类',
                'db_table': 'courses',
                'verbose_name_plural': '课程分类',
            },
        ),
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.IntegerField(blank=True, null=True, verbose_name='序号')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='标题')),
                ('choices', models.CharField(blank=True, max_length=500, verbose_name='选择内容')),
                ('answers', models.CharField(blank=True, max_length=20, verbose_name='答案')),
                ('images', models.CharField(blank=True, max_length=200, verbose_name='图片')),
                ('kind', models.IntegerField(default=1, verbose_name='题目类型')),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='problems.Chapter', verbose_name='所属章节')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='problems.Course', verbose_name='所属课程')),
            ],
            options={
                'verbose_name': '题目',
                'db_table': 'problems',
                'verbose_name_plural': '题目',
            },
        ),
        migrations.AddField(
            model_name='chapter',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='problems.Course', verbose_name='课程分类'),
        ),
    ]
