# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-08 17:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryTemp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.IntegerField(verbose_name='知识模块id')),
                ('group', models.IntegerField(verbose_name='所属项目num')),
                ('name', models.CharField(max_length=100, verbose_name='知识模块')),
            ],
            options={
                'db_table': 'category_temp',
                'verbose_name': '知识模块(未处理)',
                'verbose_name_plural': '知识模块(未处理)',
            },
        ),
        migrations.CreateModel(
            name='CourseTemp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.IntegerField(verbose_name='项目id')),
                ('name', models.CharField(max_length=100, verbose_name='项目名称')),
            ],
            options={
                'db_table': 'course_temp',
                'verbose_name': '项目(未处理)',
                'verbose_name_plural': '项目(未处理)',
            },
        ),
        migrations.CreateModel(
            name='ProbelmTemp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.IntegerField(verbose_name='所属章节id')),
                ('categoty', models.IntegerField(verbose_name='所属课程id')),
                ('num', models.IntegerField(blank=True, null=True, verbose_name='序号')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='标题')),
                ('choices', models.CharField(blank=True, max_length=500, verbose_name='选择内容')),
                ('answers', models.CharField(blank=True, max_length=20, verbose_name='答案')),
                ('images', models.CharField(blank=True, max_length=200, verbose_name='图片')),
                ('radio', models.IntegerField(verbose_name='题目类型')),
            ],
            options={
                'db_table': 'problem_temp',
                'verbose_name': '题目(未处理)',
                'verbose_name_plural': '题目(未处理)',
            },
        ),
    ]
