# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-08 06:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProbelmTemp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.IntegerField(verbose_name='所属章节id')),
                ('categoty', models.IntegerField(verbose_name='所属课程id')),
                ('num', models.IntegerField(blank=True, null=True, verbose_name='序号')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='标题')),
                ('choices', models.CharField(blank=True, max_length=500, verbose_name='选择内容')),
                ('answers', models.CharField(blank=True, max_length=20, verbose_name='答案')),
                ('images', models.CharField(blank=True, max_length=200, verbose_name='图片')),
                ('radio', models.IntegerField(verbose_name='题目类型')),
            ],
        ),
    ]
