# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-09 03:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='probelmtemp',
            old_name='radio',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='probelmtemp',
            old_name='group',
            new_name='chapter',
        ),
        migrations.RenameField(
            model_name='probelmtemp',
            old_name='categoty',
            new_name='course',
        ),
    ]
