# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-05 10:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0002_auto_20170802_1429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='probelmtemp',
            name='title',
            field=models.CharField(blank=True, max_length=600, verbose_name='标题'),
        ),
    ]
