# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-09 04:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0002_auto_20170709_1126'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CategoryTemp',
            new_name='ChapterTemp',
        ),
        migrations.RenameField(
            model_name='chaptertemp',
            old_name='group',
            new_name='course',
        ),
        migrations.AlterField(
            model_name='probelmtemp',
            name='category',
            field=models.IntegerField(choices=[(0, '单选题'), (1, '判断题'), (2, '多选题'), (3, '图片题')], default=0, verbose_name='题目类型'),
        ),
        migrations.AlterField(
            model_name='probelmtemp',
            name='images',
            field=models.ImageField(blank=True, max_length=200, upload_to='yhpicture', verbose_name='图片'),
        ),
        migrations.AlterModelTable(
            name='chaptertemp',
            table='chapters_temp',
        ),
        migrations.AlterModelTable(
            name='coursetemp',
            table='courses_temp',
        ),
        migrations.AlterModelTable(
            name='probelmtemp',
            table='problems_temp',
        ),
    ]
