# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-08 06:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0002_probelmtemp'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='probelmtemp',
            options={'verbose_name': '题目', 'verbose_name_plural': '题目'},
        ),
        migrations.AlterModelTable(
            name='probelmtemp',
            table='problem_temp',
        ),
    ]
