# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-09 08:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0003_auto_20170709_1251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='probelmtemp',
            name='chapter',
            field=models.IntegerField(verbose_name='所属课程id'),
        ),
        migrations.AlterField(
            model_name='probelmtemp',
            name='course',
            field=models.IntegerField(verbose_name='所属章节id'),
        ),
    ]
