# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-07 12:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0003_auto_20170805_1857'),
    ]

    operations = [
        migrations.AddField(
            model_name='chaptertemp',
            name='level',
            field=models.IntegerField(choices=[(0, '全国'), (1, '省级')], default=0, verbose_name='题目级别'),
        ),
        migrations.AddField(
            model_name='probelmtemp',
            name='level',
            field=models.IntegerField(choices=[(0, '全国'), (1, '省级')], default=0, verbose_name='题目级别'),
        ),
    ]
