# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-21 16:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0004_auto_20170807_2039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='probelmtemp',
            name='category',
            field=models.IntegerField(choices=[(0, '单选题'), (1, '判断题'), (2, '多选题'), (3, '图片题'), (4, '数字类选择题')], default=0, verbose_name='题目类型'),
        ),
    ]
