# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-08 07:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0004_categorytemp'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categorytemp',
            options={'verbose_name': '章节(未处理)', 'verbose_name_plural': '章节(未处理)'},
        ),
        migrations.AlterModelOptions(
            name='chapter',
            options={'verbose_name': '知识模块', 'verbose_name_plural': '知识模块'},
        ),
        migrations.AlterModelOptions(
            name='course',
            options={'verbose_name': '项目', 'verbose_name_plural': '项目'},
        ),
        migrations.AlterModelOptions(
            name='probelmtemp',
            options={'verbose_name': '题目(未处理)', 'verbose_name_plural': '题目(未处理)'},
        ),
        migrations.AlterField(
            model_name='chapter',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='problems.Course', verbose_name='项目'),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='name',
            field=models.CharField(blank=True, max_length=100, verbose_name='知识模块'),
        ),
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(blank=True, max_length=100, verbose_name='项目名称'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='chapter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='problems.Chapter', verbose_name='所属知识模块'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='problems.Course', verbose_name='所属项目'),
        ),
    ]
