# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-08 07:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0005_auto_20170708_1527'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseTemp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.IntegerField(verbose_name='项目id')),
                ('name', models.CharField(max_length=100, verbose_name='项目名称')),
            ],
            options={
                'verbose_name': '项目(未处理)',
                'verbose_name_plural': '项目(未处理)',
                'db_table': 'course_temp',
            },
        ),
        migrations.AlterModelOptions(
            name='categorytemp',
            options={'verbose_name': '知识模块(未处理)', 'verbose_name_plural': '知识模块(未处理)'},
        ),
        migrations.AlterField(
            model_name='categorytemp',
            name='group',
            field=models.IntegerField(verbose_name='所属项目num'),
        ),
        migrations.AlterField(
            model_name='categorytemp',
            name='name',
            field=models.CharField(max_length=100, verbose_name='知识模块'),
        ),
        migrations.AlterField(
            model_name='categorytemp',
            name='num',
            field=models.IntegerField(verbose_name='知识模块id'),
        ),
    ]
