# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-08 04:49
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.IntegerField(choices=[(0, '叉车--叉车司机(N2)'), (1, '叉车--场(厂)内专用机动车辆安全管理(A8)'), (2, '容器--场固定式压力容器操作(R1)'), (3, '容器--锅炉压力容器压力管道安全管理(全部)(A3)'), (4, '电梯--安全管理(A4)'), (5, '电梯--司机(T3)')], default=0, verbose_name='项目')),
                ('level', models.IntegerField(choices=[(0, '全国'), (1, '省级')], default=0, verbose_name='等级')),
                ('problem_str', models.CharField(blank=True, max_length=500, verbose_name='题目列表')),
                ('error_str', models.CharField(blank=True, max_length=500, verbose_name='错题列表')),
                ('score', models.IntegerField(default=0, verbose_name='得分')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='相关用户')),
            ],
            options={
                'verbose_name_plural': '考试',
                'verbose_name': '考试',
                'db_table': 'exams',
            },
        ),
    ]
